
1. Instalar librerías
---

In [ ]:
!pip install meteostat==1.6.8 --no-deps -q
!pip install openpyxl tqdm -q

2. Montar Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

3. Importar librerías

In [ ]:
from pathlib import Path
from datetime import datetime, date, time, timedelta
import pandas as pd
import numpy as np
import re
from tqdm import tqdm

# Fix para Meteostat con NumPy moderno
if not hasattr(np, "NaN"):
    np.NaN = np.nan

from meteostat import Point, Hourly

tqdm.pandas()

print("Entorno cargado correctamente")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Entorno cargado correctamente
Pandas: 2.2.2
NumPy: 2.0.2

4. Definir rutas

In [ ]:
ruta_archivo = Path('/content/drive/MyDrive/Final_Esp_Data/Dataset_Clima.xlsx')
carpeta = Path('/content/drive/MyDrive/Final_Esp_Data')

ruta_salida_excel = carpeta / 'Dataset_Clima_Con_Historico.xlsx'
ruta_salida_csv = carpeta / 'Dataset_Clima_Con_Historico.csv'

print("Archivo existe:", ruta_archivo.exists())

Archivo existe: True

5. Cargar archivo

In [ ]:
df = pd.read_excel(ruta_archivo)
df.columns = df.columns.str.strip()

print("Filas:", len(df))
print("Columnas:", df.columns.tolist())

df.head()

Filas: 1645
Columnas: ['Longitud Sexa finca', 'Latitud Sexa finca', 'Municipio Finca', 'HORA INICIO TURNO', 'HORA FIN TURNO', 'FINCA', 'FECHA']

,Longitud Sexa finca,Latitud Sexa finca,Municipio Finca,HORA INICIO TURNO,HORA FIN TURNO,FINCA,FECHA
0,75°50'28.7''W,4°10'32.5''N,Sevilla,06:00:00,14:00:00,13INDOS,2026-01-01
1,75°50'28.7''W,4°10'32.5''N,Sevilla,14:00:00,22:00:00,13INDOS,2026-01-01
2,75°51'47.2''W,4°07'04.0''N,Sevilla,06:00:00,14:00:00,13CRIST,2026-01-01
3,75°51'47.2''W,4°07'04.0''N,Sevilla,14:00:00,22:00:00,13CRIST,2026-01-01
4,75°50'28.7''W,4°10'32.5''N,Sevilla,06:00:00,14:00:00,13INDOS,2026-01-02

6. Validar columnas requeridas

In [ ]:
columnas_requeridas = [
    "Longitud Sexa finca",
    "Latitud Sexa finca",
    "Municipio Finca",
    "HORA INICIO TURNO",
    "HORA FIN TURNO",
    "FECHA"
]

faltantes = [c for c in columnas_requeridas if c not in df.columns]

if faltantes:
    raise ValueError(f"Faltan columnas obligatorias: {faltantes}")

print("Columnas obligatorias completas")

Columnas obligatorias completas

7. Funciones de limpieza

In [ ]:
def dms_to_decimal(valor):
    if pd.isna(valor):
        return np.nan

    texto = str(valor).strip().upper()
    texto = texto.replace("''", '"')
    texto = texto.replace("″", '"')
    texto = texto.replace("”", '"')
    texto = texto.replace("’", "'")
    texto = texto.replace("′", "'")
    texto = texto.replace(" ", "")

    patron = r"(\d+(?:\.\d+)?)°(\d+(?:\.\d+)?)'(\d+(?:\.\d+)?)\"?([NSEW])"
    match = re.search(patron, texto)

    if match:
        grados = float(match.group(1))
        minutos = float(match.group(2))
        segundos = float(match.group(3))
        direccion = match.group(4)

        decimal = grados + minutos / 60 + segundos / 3600

        if direccion in ["S", "W"]:
            decimal *= -1

        return decimal

    try:
        return float(texto.replace(",", "."))
    except:
        return np.nan


def extraer_hora(valor):
    if pd.isna(valor):
        return None

    if isinstance(valor, time):
        return valor

    if isinstance(valor, datetime):
        return valor.time()

    texto = str(valor).strip()

    try:
        return pd.to_datetime(texto, errors="coerce").time()
    except:
        return None


def construir_datetime(fecha_valor, hora_valor):
    fecha = pd.to_datetime(fecha_valor, errors="coerce")

    if pd.isna(fecha):
        return pd.NaT

    hora = extraer_hora(hora_valor)

    if hora is None:
        return pd.NaT

    return datetime.combine(fecha.date(), hora)


def clasificar_lluvia(mm):
    if pd.isna(mm):
        return "Sin dato"

    if mm > 0:
        return "Lluvioso"

    return "Seco"

8. Preparar coordenadas, fechas y horas

In [ ]:
df["lat_decimal"] = df["Latitud Sexa finca"].apply(dms_to_decimal)
df["lon_decimal"] = df["Longitud Sexa finca"].apply(dms_to_decimal)

df["fecha_dt"] = pd.to_datetime(df["FECHA"], errors="coerce")

df["hora_inicio_turno_dt"] = df.apply(
    lambda row: construir_datetime(row["FECHA"], row["HORA INICIO TURNO"]),
    axis=1
)

df["hora_fin_turno_dt"] = df.apply(
    lambda row: construir_datetime(row["FECHA"], row["HORA FIN TURNO"]),
    axis=1
)

# Si el turno termina al día siguiente
df.loc[
    df["hora_fin_turno_dt"] <= df["hora_inicio_turno_dt"],
    "hora_fin_turno_dt"
] = df["hora_fin_turno_dt"] + timedelta(days=1)

df[[
    "Longitud Sexa finca",
    "Latitud Sexa finca",
    "lat_decimal",
    "lon_decimal",
    "FECHA",
    "HORA INICIO TURNO",
    "hora_inicio_turno_dt",
    "HORA FIN TURNO",
    "hora_fin_turno_dt"
]].head()

,Longitud Sexa finca,Latitud Sexa finca,lat_decimal,lon_decimal,FECHA,HORA INICIO TURNO,hora_inicio_turno_dt,HORA FIN TURNO,hora_fin_turno_dt
0,75°50'28.7''W,4°10'32.5''N,4.175694,-75.841306,2026-01-01,06:00:00,2026-01-01 06:00:00,14:00:00,2026-01-01 14:00:00
1,75°50'28.7''W,4°10'32.5''N,4.175694,-75.841306,2026-01-01,14:00:00,2026-01-01 14:00:00,22:00:00,2026-01-01 22:00:00
2,75°51'47.2''W,4°07'04.0''N,4.117778,-75.863111,2026-01-01,06:00:00,2026-01-01 06:00:00,14:00:00,2026-01-01 14:00:00
3,75°51'47.2''W,4°07'04.0''N,4.117778,-75.863111,2026-01-01,14:00:00,2026-01-01 14:00:00,22:00:00,2026-01-01 22:00:00
4,75°50'28.7''W,4°10'32.5''N,4.175694,-75.841306,2026-01-02,06:00:00,2026-01-02 06:00:00,14:00:00,2026-01-02 14:00:00

9. Validación crítica

In [ ]:
print("Total registros:", len(df))
print("Sin latitud:", df["lat_decimal"].isna().sum())
print("Sin longitud:", df["lon_decimal"].isna().sum())
print("Sin fecha:", df["fecha_dt"].isna().sum())
print("Sin hora inicio:", df["hora_inicio_turno_dt"].isna().sum())
print("Sin hora fin:", df["hora_fin_turno_dt"].isna().sum())

Total registros: 1645
Sin latitud: 0
Sin longitud: 0
Sin fecha: 0
Sin hora inicio: 2
Sin hora fin: 2

10. Función optimizada para consultar Meteostat

In [ ]:
cache_clima = {}

def consultar_clima_turno(row):
    lat = row["lat_decimal"]
    lon = row["lon_decimal"]
    inicio = row["hora_inicio_turno_dt"]
    fin = row["hora_fin_turno_dt"]

    if pd.isna(lat) or pd.isna(lon) or pd.isna(inicio) or pd.isna(fin):
        return pd.Series({
            "clima_temp_inicio_c": np.nan,
            "clima_precipitacion_inicio_mm": np.nan,
            "clima_estado_inicio": "Sin dato",
            "clima_precipitacion_turno_mm": np.nan,
            "clima_estado_turno": "Sin dato",
            "clima_humedad_promedio": np.nan,
            "clima_viento_promedio_kmh": np.nan,
            "clima_presion_promedio_hpa": np.nan,
            "clima_horas_consultadas": 0,
            "clima_observacion": "Datos insuficientes"
        })

    inicio = inicio.replace(minute=0, second=0, microsecond=0)
    fin = fin.replace(minute=0, second=0, microsecond=0)

    if fin <= inicio:
        fin = inicio + timedelta(hours=1)

    key = (
        round(float(lat), 5),
        round(float(lon), 5),
        inicio.strftime("%Y-%m-%d %H:%M:%S"),
        fin.strftime("%Y-%m-%d %H:%M:%S")
    )

    if key in cache_clima:
        return cache_clima[key]

    try:
        punto = Point(float(lat), float(lon))
        data = Hourly(punto, inicio, fin).fetch()

        if data.empty:
            resultado = pd.Series({
                "clima_temp_inicio_c": np.nan,
                "clima_precipitacion_inicio_mm": np.nan,
                "clima_estado_inicio": "Sin dato",
                "clima_precipitacion_turno_mm": np.nan,
                "clima_estado_turno": "Sin dato",
                "clima_humedad_promedio": np.nan,
                "clima_viento_promedio_kmh": np.nan,
                "clima_presion_promedio_hpa": np.nan,
                "clima_horas_consultadas": 0,
                "clima_observacion": "Meteostat no encontró datos para esa fecha/hora"
            })

            cache_clima[key] = resultado
            return resultado

        primera_hora = data.iloc[0]

        temp_inicio = primera_hora.get("temp", np.nan)
        prcp_inicio = primera_hora.get("prcp", np.nan)

        prcp_turno = data["prcp"].sum(skipna=True) if "prcp" in data.columns else np.nan
        humedad_prom = data["rhum"].mean(skipna=True) if "rhum" in data.columns else np.nan
        viento_prom = data["wspd"].mean(skipna=True) if "wspd" in data.columns else np.nan
        presion_prom = data["pres"].mean(skipna=True) if "pres" in data.columns else np.nan

        resultado = pd.Series({
            "clima_temp_inicio_c": temp_inicio,
            "clima_precipitacion_inicio_mm": prcp_inicio,
            "clima_estado_inicio": clasificar_lluvia(prcp_inicio),
            "clima_precipitacion_turno_mm": prcp_turno,
            "clima_estado_turno": clasificar_lluvia(prcp_turno),
            "clima_humedad_promedio": humedad_prom,
            "clima_viento_promedio_kmh": viento_prom,
            "clima_presion_promedio_hpa": presion_prom,
            "clima_horas_consultadas": len(data),
            "clima_observacion": "Dato obtenido correctamente"
        })

        cache_clima[key] = resultado
        return resultado

    except Exception as e:
        resultado = pd.Series({
            "clima_temp_inicio_c": np.nan,
            "clima_precipitacion_inicio_mm": np.nan,
            "clima_estado_inicio": "Error",
            "clima_precipitacion_turno_mm": np.nan,
            "clima_estado_turno": "Error",
            "clima_humedad_promedio": np.nan,
            "clima_viento_promedio_kmh": np.nan,
            "clima_presion_promedio_hpa": np.nan,
            "clima_horas_consultadas": 0,
            "clima_observacion": str(e)
        })

        cache_clima[key] = resultado
        return resultado

11. Ejecutar consulta climática

In [ ]:
df_clima = df.progress_apply(consultar_clima_turno, axis=1)

df_final = pd.concat([df, df_clima], axis=1)

df_final["fue_lluvioso_en_inicio"] = df_final["clima_precipitacion_inicio_mm"].apply(
    lambda x: "Sí" if pd.notna(x) and x > 0 else ("No" if pd.notna(x) else "Sin dato")
)

df_final["fue_lluvioso_en_turno"] = df_final["clima_precipitacion_turno_mm"].apply(
    lambda x: "Sí" if pd.notna(x) and x > 0 else ("No" if pd.notna(x) else "Sin dato")
)

df_final.head()

  1%|          | 11/1645 [00:01<01:53, 14.45it/s]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  1%|          | 14/1645 [00:01<02:37, 10.38it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  2%|▏         | 28/1645 [00:01<01:03, 25.54it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  2%|▏         | 32/1645 [00:01<00:57, 28.04it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  2%|▏         | 41/1645 [00:02<00:47, 33.60it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  3%|▎         | 45/1645 [00:02<00:46, 34.69it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  3%|▎         | 53/1645 [00:02<00:44, 35.51it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  4%|▎         | 58/1645 [00:02<00:41, 37.91it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  4%|▍         | 62/1645 [00:02<00:41, 38.08it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  4%|▍         | 67/1645 [00:02<00:39, 39.54it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  4%|▍         | 72/1645 [00:02<00:37, 41.97it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  5%|▍         | 80/1645 [00:03<00:30, 51.47it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  8%|▊         | 132/1645 [00:04<00:26, 57.11it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  9%|▊         | 143/1645 [00:04<00:21, 69.97it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  9%|▉         | 151/1645 [00:04<00:26, 56.04it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 10%|▉         | 158/1645 [00:04<00:30, 49.49it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 10%|▉         | 164/1645 [00:04<00:31, 46.74it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 14%|█▍        | 231/1645 [00:05<00:17, 81.58it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 15%|█▌        | 248/1645 [00:05<00:22, 61.18it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 16%|█▌        | 255/1645 [00:06<00:24, 56.70it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 16%|█▌        | 261/1645 [00:06<00:24, 55.78it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 17%|█▋        | 273/1645 [00:06<00:26, 51.39it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 17%|█▋        | 279/1645 [00:06<00:26, 50.87it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 18%|█▊        | 290/1645 [00:06<00:28, 47.22it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 18%|█▊        | 296/1645 [00:06<00:28, 48.03it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 22%|██▏       | 366/1645 [00:08<00:24, 51.36it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 23%|██▎       | 372/1645 [00:08<00:28, 45.35it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 23%|██▎       | 377/1645 [00:08<00:31, 39.72it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 23%|██▎       | 385/1645 [00:08<00:26, 47.18it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 24%|██▍       | 391/1645 [00:08<00:32, 38.45it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 24%|██▍       | 396/1645 [00:09<00:33, 37.58it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 25%|██▍       | 404/1645 [00:09<00:28, 43.53it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 27%|██▋       | 439/1645 [00:10<00:28, 42.47it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 30%|██▉       | 488/1645 [00:12<00:40, 28.51it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 30%|██▉       | 492/1645 [00:13<00:43, 26.74it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 32%|███▏      | 523/1645 [00:13<00:16, 68.54it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 32%|███▏      | 531/1645 [00:13<00:21, 52.22it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 33%|███▎      | 538/1645 [00:13<00:22, 50.22it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 35%|███▍      | 572/1645 [00:14<00:18, 59.41it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 35%|███▌      | 579/1645 [00:14<00:20, 52.50it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 36%|███▌      | 585/1645 [00:14<00:20, 50.63it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 36%|███▋      | 599/1645 [00:15<00:18, 56.88it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 38%|███▊      | 623/1645 [00:15<00:19, 51.33it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 38%|███▊      | 629/1645 [00:15<00:20, 49.55it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 41%|████      | 669/1645 [00:16<00:25, 37.63it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 41%|████      | 676/1645 [00:16<00:23, 41.42it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 42%|████▏     | 698/1645 [00:17<00:27, 35.04it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 43%|████▎     | 702/1645 [00:17<00:26, 35.97it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 43%|████▎     | 708/1645 [00:17<00:23, 39.47it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 45%|████▌     | 748/1645 [00:18<00:31, 28.59it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 46%|████▌     | 754/1645 [00:19<00:25, 34.32it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 47%|████▋     | 780/1645 [00:19<00:20, 43.14it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 48%|████▊     | 785/1645 [00:19<00:20, 42.74it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 51%|█████     | 831/1645 [00:20<00:17, 46.59it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 51%|█████     | 837/1645 [00:20<00:16, 49.24it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 52%|█████▏    | 851/1645 [00:21<00:14, 55.85it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 52%|█████▏    | 863/1645 [00:21<00:14, 55.85it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 53%|█████▎    | 869/1645 [00:21<00:14, 52.12it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 53%|█████▎    | 875/1645 [00:21<00:14, 52.06it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 54%|█████▍    | 887/1645 [00:21<00:15, 50.26it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 54%|█████▍    | 893/1645 [00:21<00:14, 51.85it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 55%|█████▌    | 907/1645 [00:22<00:12, 58.93it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 56%|█████▌    | 913/1645 [00:22<00:15, 47.72it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 56%|█████▌    | 919/1645 [00:22<00:16, 44.64it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 56%|█████▌    | 924/1645 [00:22<00:19, 37.78it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 57%|█████▋    | 934/1645 [00:22<00:19, 36.12it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 57%|█████▋    | 938/1645 [00:23<00:24, 28.73it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 58%|█████▊    | 946/1645 [00:23<00:29, 23.98it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 58%|█████▊    | 949/1645 [00:23<00:43, 15.83it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 58%|█████▊    | 960/1645 [00:24<00:53, 12.72it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 59%|█████▊    | 965/1645 [00:25<00:46, 14.57it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 59%|█████▉    | 971/1645 [00:25<00:40, 16.75it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 59%|█████▉    | 975/1645 [00:25<00:33, 19.83it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 60%|█████▉    | 981/1645 [00:25<00:28, 23.11it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 60%|█████▉    | 985/1645 [00:26<00:27, 24.08it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
 60%|██████    | 991/1645 [00:26<00:32, 19.91it/s]FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.

,Longitud Sexa finca,Latitud Sexa finca,Municipio Finca,HORA INICIO TURNO,HORA FIN TURNO,FINCA,FECHA,lat_decimal,lon_decimal,fecha_dt,...,clima_estado_inicio,clima_precipitacion_turno_mm,clima_estado_turno,clima_humedad_promedio,clima_viento_promedio_kmh,clima_presion_promedio_hpa,clima_horas_consultadas,clima_observacion,fue_lluvioso_en_inicio,fue_lluvioso_en_turno
0,75°50'28.7''W,4°10'32.5''N,Sevilla,06:00:00,14:00:00,13INDOS,2026-01-01,4.175694,-75.841306,2026-01-01,...,Sin dato,NaN,Sin dato,NaN,NaN,NaN,0,Meteostat no encontró datos para esa fecha/hora,Sin dato,Sin dato
1,75°50'28.7''W,4°10'32.5''N,Sevilla,14:00:00,22:00:00,13INDOS,2026-01-01,4.175694,-75.841306,2026-01-01,...,Sin dato,NaN,Sin dato,NaN,NaN,NaN,0,Meteostat no encontró datos para esa fecha/hora,Sin dato,Sin dato
2,75°51'47.2''W,4°07'04.0''N,Sevilla,06:00:00,14:00:00,13CRIST,2026-01-01,4.117778,-75.863111,2026-01-01,...,Sin dato,NaN,Sin dato,NaN,NaN,NaN,0,Meteostat no encontró datos para esa fecha/hora,Sin dato,Sin dato
3,75°51'47.2''W,4°07'04.0''N,Sevilla,14:00:00,22:00:00,13CRIST,2026-01-01,4.117778,-75.863111,2026-01-01,...,Sin dato,NaN,Sin dato,NaN,NaN,NaN,0,Meteostat no encontró datos para esa fecha/hora,Sin dato,Sin dato
4,75°50'28.7''W,4°10'32.5''N,Sevilla,06:00:00,14:00:00,13INDOS,2026-01-02,4.175694,-75.841306,2026-01-02,...,Sin dato,NaN,Sin dato,NaN,NaN,NaN,0,Meteostat no encontró datos para esa fecha/hora,Sin dato,Sin dato

12. Revisar resultados

In [ ]:
print("Resumen clima hora inicio:")
print(df_final["clima_estado_inicio"].value_counts(dropna=False))

print("\nResumen clima durante turno:")
print(df_final["clima_estado_turno"].value_counts(dropna=False))

df_final[[
    "Municipio Finca",
    "FINCA" if "FINCA" in df_final.columns else "Municipio Finca",
    "FECHA",
    "HORA INICIO TURNO",
    "HORA FIN TURNO",
    "lat_decimal",
    "lon_decimal",
    "clima_temp_inicio_c",
    "clima_precipitacion_inicio_mm",
    "clima_estado_inicio",
    "clima_precipitacion_turno_mm",
    "clima_estado_turno",
    "fue_lluvioso_en_turno",
    "clima_observacion"
]].head(20)

Resumen clima hora inicio:
clima_estado_inicio
Sin dato    1400
Seco         156
Lluvioso      89
Name: count, dtype: int64

Resumen clima durante turno:
clima_estado_turno
Sin dato    1355
Lluvioso     199
Seco          91
Name: count, dtype: int64

,Municipio Finca,FINCA,FECHA,HORA INICIO TURNO,HORA FIN TURNO,lat_decimal,lon_decimal,clima_temp_inicio_c,clima_precipitacion_inicio_mm,clima_estado_inicio,clima_precipitacion_turno_mm,clima_estado_turno,fue_lluvioso_en_turno,clima_observacion
0,Sevilla,13INDOS,2026-01-01,06:00:00,14:00:00,4.175694,-75.841306,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
1,Sevilla,13INDOS,2026-01-01,14:00:00,22:00:00,4.175694,-75.841306,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
2,Sevilla,13CRIST,2026-01-01,06:00:00,14:00:00,4.117778,-75.863111,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
3,Sevilla,13CRIST,2026-01-01,14:00:00,22:00:00,4.117778,-75.863111,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
4,Sevilla,13INDOS,2026-01-02,06:00:00,14:00:00,4.175694,-75.841306,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
5,Sevilla,13INDOS,2026-01-02,14:00:00,22:00:00,4.175694,-75.841306,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
6,Sevilla,13CRIST,2026-01-02,06:00:00,14:00:00,4.117778,-75.863111,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
7,Sevilla,13CRIST,2026-01-02,14:00:00,22:00:00,4.117778,-75.863111,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
8,Bolivar,35PLAYA,2026-01-02,06:00:00,14:00:00,4.425917,-76.263222,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
9,Bolivar,35PLAYA,2026-01-02,14:00:00,22:00:00,4.425917,-76.263222,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
10,Bolivar,35PLAYA,2026-01-02,06:00:00,14:00:00,4.425917,-76.263222,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
11,Cumbre,32PORRA,2026-01-02,06:00:00,14:00:00,3.694389,-76.573056,21.0,0.0,Seco,0.6,Lluvioso,Sí,Dato obtenido correctamente
12,Cumbre,32PORRA,2026-01-02,14:00:00,22:00:00,3.694389,-76.573056,23.0,0.1,Lluvioso,1.7,Lluvioso,Sí,Dato obtenido correctamente
13,Cumbre,32PORRA,2026-01-03,14:00:00,22:00:00,3.694389,-76.573056,23.0,0.1,Lluvioso,16.3,Lluvioso,Sí,Dato obtenido correctamente
14,Cumbre,32PORRA,2026-01-03,06:00:00,14:00:00,3.694389,-76.573056,21.0,0.0,Seco,0.2,Lluvioso,Sí,Dato obtenido correctamente
15,Restrepo,34SUIZA,2026-01-03,22:00:00,06:00:00,3.841944,-76.490389,28.0,1.0,Lluvioso,8.1,Lluvioso,Sí,Dato obtenido correctamente
16,Riofrio,31GRACI,2026-01-03,06:00:00,14:00:00,4.069972,-76.407444,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
17,Riofrio,31GRACI,2026-01-03,14:00:00,22:00:00,4.069972,-76.407444,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
18,Riofrio,31GRACI,2026-01-03,06:00:00,14:00:00,4.069972,-76.407444,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora
19,Riofrio,31GRACI,2026-01-03,14:00:00,22:00:00,4.069972,-76.407444,NaN,NaN,Sin dato,NaN,Sin dato,Sin dato,Meteostat no encontró datos para esa fecha/hora

In [ ]:
total = len(df_final)
sin_data = df_final["clima_observacion"].str.contains("no encontró", case=False, na=False).sum()

print(f"Sin data: {sin_data} ({sin_data/total:.2%})")

Sin data: 1353 (82.25%)

13. Guardar archivo final

In [ ]:
df_final.to_excel(ruta_salida_excel, index=False)
df_final.to_csv(ruta_salida_csv, index=False, encoding="utf-8-sig")

print("Archivo Excel generado:")
print(ruta_salida_excel)

print("Archivo CSV generado:")
print(ruta_salida_csv)